#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : khal
Version  : 0.10.1
Release  : 32
URL      : https://files.pythonhosted.org/packages/f7/45/555398810c14f572ea9ff8e92cd4f6e492ba8c50da1241fad58e58234463/khal-0.10.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/f7/45/555398810c14f572ea9ff8e92cd4f6e492ba8c50da1241fad58e58234463/khal-0.10.1.tar.gz
Summary  : CLI calendar application build around CalDAV
Group    : Development/Tools
License  : MIT
Requires: khal-bin = %{version}-%{release}
Requires: khal-data = %{version}-%{release}
Requires: khal-license = %{version}-%{release}
Requires: khal-python = %{version}-%{release}
Requires: khal-python3 = %{version}-%{release}
Requires: atomicwrites
Requires: click
Requires: click-log
Requires: configobj
Requires: icalendar
Requires: python-dateutil
Requires: python-urwid
Requires: pytz
Requires: pyxdg
Requires: setproctitle
Requires: typing
Requires: tzlocal
BuildRequires : atomicwrites
BuildRequires : buildreq-distutils3
BuildRequires : click
BuildRequires : click-log
BuildRequires : configobj
BuildRequires : icalendar
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dateutil
BuildRequires : python-urwid
BuildRequires : pytz
BuildRequires : pyxdg
BuildRequires : setproctitle
BuildRequires : setuptools_scm
BuildRequires : tox
BuildRequires : typing
BuildRequires : tzlocal
BuildRequires : virtualenv

%description
khal
====
.. image:: https://travis-ci.org/pimutils/khal.svg?branch=master
    :target: https://travis-ci.org/pimutils/khal

.. image:: https://codecov.io/github/pimutils/khal/coverage.svg?branch=master
  :target: https://codecov.io/github/pimutils/khal?branch=master

*Khal* is a standards based CLI and terminal calendar program, able to synchronize
with CalDAV_ servers through vdirsyncer_.

.. image:: http://lostpackets.de/images/khal.png

Features
--------
(or rather: limitations)

- khal can read and write events/icalendars to vdir_, so vdirsyncer_ can be
  used to `synchronize calendars with a variety of other programs`__, for
  example CalDAV_ servers.
- fast and easy way to add new events
- ikhal (interactive khal) lets you browse and edit calendars and events
- no support for editing the timezones of events yet
- works with python 3.4+
- khal should run on all major operating systems [1]_

.. [1] except for Microsoft Windows

Feedback
--------
Please do provide feedback if *khal* works for you or even more importantly if
it doesn't. The preferred way to get in contact (especially if something isn't
working) is via github or IRC (#pimutils on Freenode), otherwise you can reach
the original author via email at khal (at) lostpackets (dot) de or via
jabber/XMPP at geier (at) jabber (dot) ccc (dot) de.

.. _vdir: https://vdirsyncer.readthedocs.org/en/stable/vdir.html
.. _vdirsyncer: https://github.com/pimutils/vdirsyncer
.. _CalDAV: http://en.wikipedia.org/wiki/CalDAV
.. _github: https://github.com/pimutils/khal/
.. __: http://en.wikipedia.org/wiki/Comparison_of_CalDAV_and_CardDAV_implementations


Documentation
-------------
For khal's documentation have a look at the website_ or readthedocs_.

.. _website: https://lostpackets.de/khal/
.. _readthedocs: http://khal.readthedocs.org/


Alternatives
------------
Projects with similar aims you might want to check out are calendar-cli_ (no
offline storage and a bit different scope) and gcalcli_ (only works with
google's calendar).

.. _calendar-cli: https://github.com/tobixen/calendar-cli
.. _gcalcli: https://github.com/insanum/gcalcli

Contributing
------------
You want to contribute to *khal*? Awesome!

The most appreciated way of contributing is by supplying code or documentation,
reporting bugs, creating packages for your favorite operating system, making
khal better known by telling your friends about it, etc.

License
-------
khal is released under the Expat/MIT License::

    Copyright (c) 2013-2017 Christian Geier et al.

    Permission is hereby granted, free of charge, to any person obtaining a copy of
    this software and associated documentation files (the "Software"), to deal in
    the Software without restriction, including without limitation the rights to
    use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
    the Software, and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
    FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
    COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
    IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
    CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

%package bin
Summary: bin components for the khal package.
Group: Binaries
Requires: khal-data = %{version}-%{release}
Requires: khal-license = %{version}-%{release}

%description bin
bin components for the khal package.


%package data
Summary: data components for the khal package.
Group: Data

%description data
data components for the khal package.


%package license
Summary: license components for the khal package.
Group: Default

%description license
license components for the khal package.


%package python
Summary: python components for the khal package.
Group: Default
Requires: khal-python3 = %{version}-%{release}

%description python
python components for the khal package.


%package python3
Summary: python3 components for the khal package.
Group: Default
Requires: python3-core
Provides: pypi(khal)

%description python3
python3 components for the khal package.


%prep
%setup -q -n khal-0.10.1
cd %{_builddir}/khal-0.10.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583164852
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/khal
cp %{_builddir}/khal-0.10.1/COPYING %{buildroot}/usr/share/package-licenses/khal/918f3b8f569ca951b053df0aa458c73e219487f5
cp %{_builddir}/khal-0.10.1/doc/source/license.rst %{buildroot}/usr/share/package-licenses/khal/64df61d65c5b96d10ebba081593a79ab7905da29
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
mkdir -p %{buildroot}/usr/share/defaults/khal/
cp khal.conf.sample %{buildroot}/usr/share/defaults/khal/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ikhal
/usr/bin/khal

%files data
%defattr(-,root,root,-)
/usr/share/defaults/khal/khal.conf.sample

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/khal/64df61d65c5b96d10ebba081593a79ab7905da29
/usr/share/package-licenses/khal/918f3b8f569ca951b053df0aa458c73e219487f5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
