#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : khal
Version  : 0.9.10
Release  : 25
URL      : https://files.pythonhosted.org/packages/fc/f0/c5da6fe8b8be51b865fbc3b4ff44d9f46fe9426b69a82d5e058a64924d1b/khal-0.9.10.tar.gz
Source0  : https://files.pythonhosted.org/packages/fc/f0/c5da6fe8b8be51b865fbc3b4ff44d9f46fe9426b69a82d5e058a64924d1b/khal-0.9.10.tar.gz
Summary  : CLI calendar application build around CalDAV
Group    : Development/Tools
License  : MIT
Requires: khal-bin = %{version}-%{release}
Requires: khal-data = %{version}-%{release}
Requires: khal-license = %{version}-%{release}
Requires: khal-python = %{version}-%{release}
Requires: khal-python3 = %{version}-%{release}
Requires: atomicwrites
Requires: click
Requires: configobj
Requires: icalendar
Requires: python-dateutil
Requires: python-urwid
Requires: pytz
Requires: pyxdg
Requires: setproctitle
Requires: tzlocal
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools_scm
BuildRequires : tox
BuildRequires : virtualenv

%description
khal
====
.. image:: https://travis-ci.org/pimutils/khal.svg?branch=master
:target: https://travis-ci.org/pimutils/khal

%package bin
Summary: bin components for the khal package.
Group: Binaries
Requires: khal-data = %{version}-%{release}
Requires: khal-license = %{version}-%{release}

%description bin
bin components for the khal package.


%package data
Summary: data components for the khal package.
Group: Data

%description data
data components for the khal package.


%package license
Summary: license components for the khal package.
Group: Default

%description license
license components for the khal package.


%package python
Summary: python components for the khal package.
Group: Default
Requires: khal-python3 = %{version}-%{release}

%description python
python components for the khal package.


%package python3
Summary: python3 components for the khal package.
Group: Default
Requires: python3-core

%description python3
python3 components for the khal package.


%prep
%setup -q -n khal-0.9.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549686794
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/khal
cp COPYING %{buildroot}/usr/share/package-licenses/khal/COPYING
cp doc/source/license.rst %{buildroot}/usr/share/package-licenses/khal/doc_source_license.rst
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
mkdir -p %{buildroot}/usr/share/defaults/khal/
cp khal.conf.sample %{buildroot}/usr/share/defaults/khal/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ikhal
/usr/bin/khal

%files data
%defattr(-,root,root,-)
/usr/share/defaults/khal/khal.conf.sample

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/khal/COPYING
/usr/share/package-licenses/khal/doc_source_license.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
